baseURL = "https://signumfraud.pages.dev/"
title = "Modem & Reboot"
author= "Signum Fraud"
theme = "etch"
languageCode = "en-us"
enableInlineShortcodes = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Signum Fraud's Personal Website"
  copyright = "Copyright © 2024 Signum Fraud"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/contact/"
    weight = 15

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
